### ISSUE TITLE
Answer for your example.

### ISSUE THREAD

**Issue by jhonnynemonic** [syzdek/efibootiso#1]
Hello SYZDEK,

I tried to follow your instrucctions for create this ISO and i need say that works but your indications are not complete.

The only thing is I find isnt working the command for create the iso and work with the image on the USB. 

All of rest is right and is good explained for example create the image with grub-mkimage for be the boot EFI file of ISO.

How i get time for test your example here i post now the right command for create ISO and then i will explain why doesnt work in my case.

Right Command:

genisoimage -o output.iso -c boot.cat -b isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e EFI/BOOT/efiboot.img -no-emul-boot -input-charset default -V EFIBOOTISO .

All of this is structured with the same folder you created named EFIBOOTISO but i just added a few items in this command how can you see and in the folder without subfolder.

This files are necesary because when you try to boot the system says not found files because in your creation isohybrid can not be run right because doesnt find anything into it and the iso not complete the requeriments for be a ISO EFI file ( this is just my case because i dont have the command) or try to add the EFI file to boot to nothing can be start with this new releases:

-o output.iso - can be the of efiboot.iso but i renamed it.

-c boot.cat -- this is the general boot.cat file for add catalog to the iso and the true one can work with genisomage and isolinux for boot efiboot.img and do a EFI system and the iso works.

-b isolinux.bin -- file from syslinux for create a boot entry on the CD Boot and start ISO MODE.

When you make your standad command for create the iso here in my ditribution of Ubuntu Focal Fossa y dont have the command that say's " -eltorito-platform efi \" for create the iso and i was searching other alternatives like mkisofs or xorriso but doesnt work because the commands dont find nothing and say allways something moe is need for do the work or something is bad for create it . I next you read the actually options you can see what happend.

This is the typical errors you can find when work with this format. " Catalog not found for create iso", "Boot file dont found in the iso" and "Sectors are more higher for create the specifiy boot file". This happends when you try creation but in other cases are when you specify parameters for a floppy if you dont use -no-emul-boot in the correct space of command for example. Many of they.

So i dont know if this can help you but the EFIBOOTISO is working with this paramenters.

Perhaps you are know thinking why i added ISOLINUX for create the iso and i need must say this. If you done add this file the creation doesnt work, perhaps can be the changes.

I put my file here for share and see.

https://drive.google.com/file/d/16ZCONjtvdBqvUNEEVox6ZPi3J3a4Cszj/view?usp=sharing

**Comment by syzdek** [comment]
[jhonnynemonic](https://github.com/jhonnynemonic) I'l try to test your changes this week and update the instructions.  Have you tried [IPERD](https://github.com/syzdek/iperd)?

**Comment by jhonnynemonic** [comment]
Than you for you interest. But i dont know what is IPERD can you tell me what is?.

**Comment by jhonnynemonic** [comment]
I was looking the IPERD that you say and is interesting software but really i dont use it.

Syzdek, i have a new question and perhaps you can help me with this. Why when i burn de ISO file image to a CD the computer dont detect de iso file in te device for booting CD-ROM. I have UEFI and good PC, is new and not have more than 3 months but my BIOS doesnt find anaything about this medium when i inserted to CD-ROM.

I tried to burn other ISO like for example Ubuntu or UBCD and the medium is showed without problems and started it with no error.

Why happend this is ISO of EFIBOOTISO??

Thank you in advance.

**Comment by jhonnynemonic** [comment]
Hello my friend!!

I hace good news now with my time working with your instrucciones.

I was redone the material and here is what i hace with a mistake, no repeated.

mkdir -p efibootiso
cd efibootiso
mkdir -p EFI/BOOT
mkdir -p boot/grub/x86_64-efi
Download Slackware files:

curl \
   -o boot/vmlinuz \
   https://mirrors.kernel.org/slackware/slackware64-current/kernels/huge.s/bzImage
curl \
   -o boot/initrd.img \
   https://mirrors.kernel.org/slackware/slackware64-current/isolinux/initrd.img
Create bootx64.efi
Copy grub modules:

cp /usr/lib64/grub/x86_64-efi/*.mod boot/grub/x86_64-efi/
Create stub grub configuration:

cat << EOF > grub-stub.cfg

insmod all_video
insmod efi_gop
insmod efi_uga
insmod video_bochs
insmod video_cirrus

insmod iso9660
insmod udf

search --no-floppy --label EFIBOOTISO --set root
set prefix=($root)/boot/grub

configfile /grub.cfg

EOF
Create grub image:

grub-mkimage \
   -o EFI/BOOT/bootx64.efi \
   -c grub-stub.cfg \
   -p /boot/grub \
   -O x86_64-efi \
   efi_gop efi_uga efinet \
   all_video video video_bochs video_cirrus video_fb videoinfo \
   serial \
   terminfo terminal \
   search search_fs_file search_fs_uuid search_label \
   udf iso9660 ext2 fat exfat ntfs hfsplus \
   part_gpt part_msdos msdospart lvm diskfilter parttool probe \
   normal \
   acpi ohci uhci ahci ehci \
   cat ls chain configfile echo halt reboot \
   ls lsefimmap lsefisystab lsmmap lspci lsacpi lssal \
   linux
Create UEFI ESP (EFI System Partition) Image
Create empty file to use as disk image:

dd if=/dev/zero of=EFI/BOOT/efiboot.img bs=512 count=2880
Create MSDOS filesystem:

mkfs.msdos -F 12 -n 'EFIBOOTISO' EFI/BOOT/efiboot.img
Create directory structure:

mmd -i EFI/BOOT/efiboot.img ::EFI
mmd -i EFI/BOOT/efiboot.img ::EFI/BOOT
Copy grub image into disk image file:

mcopy -i EFI/BOOT/efiboot.img EFI/BOOT/bootx64.efi ::EFI/BOOT/bootx64.efi
Create UEFI bootable ISO image
Create full grub configuration:

cat << EOF > grub.cfg

serial --unit 4 --speed 9600
terminal_input  serial console
terminal_output serial console

set pager=1

menuentry --hotkey=l 'Linux' {
   echo   'Loading /boot/vmlinuz ...'
   linux  /boot/vmlinuz \
          console=tty0 \
          rw
   echo   'Loading /boot/initrd.img ...'
   initrd /boot/initrd.img
}
menuentry --hotkey=p 'List PCI' {
   lspci
}
menuentry --hotkey=r 'Reboot' {
   reboot
}
menuentry --hotkey=h 'Halt' {
   halt
}

EOF
Create ISO image with xorriso as mkisofs:

xorriso \
    -as mkisofs \
    -iso-level 3 \
    -o CD.iso \
    -full-iso9660-filenames \
    -volid "EFIBOOTISO" \
    --mbr-force-bootable -partition_offset 16 \
    -joliet -joliet-long -rational-rock \
    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -eltorito-boot \
        /isolinux/isolinux.bin \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        --eltorito-catalog /isolinux/boot.cat \
    -eltorito-alt-boot \
        -e EFI/BOOT/efiboot.img \
        -no-emul-boot \
        -isohybrid-gpt-basdat \
.

Why this news method i win how start the ISO image with a CDROM Bootable like a Ubuntu CD.

But happend this... The signature for boot is invalid. I think this is are very strange because Who create the bootx64.efi file is grub-mkimage with the parameters for got our instrucctions to boot. Can you help on that? I dont know why but the signature day is invalid, but web won "Bootable CD". Also is posible be grub.efi file needed??

Thank you for your time and i dont falla on repeat that this is a good work.

See you soon.

**Comment by jhonnynemonic** [comment]
Hello my friend again and stay a will and listen!!

I made the final iso working with boot and load of the system with CD-ROM fully tested.

The only bad new is the loading of the sign with linux try to boot with EFI MODE fail but is working and perhaps we will see if a one day is working.

I gona tell you how i do it and post the file with a new link for the downloading and testing. Remember only with "No boot Secure" because the signature of linux in my case is false. Perhaps in your machine or in the other guy in internet works but i dont think so, is a mistake.

Here is the link of the zip file that content the iso file. No virus included. An only need burn and test.

https://drive.google.com/file/d/1T04gh58fKuA0gIRL06wUkjTdZAhvertJ/view?usp=sharing

So, i gonna explain how i done it.

The first i was change my mind in this version whe error was showing the boot for the ISO CD-ROM "no root file isnt present" when booting machine and i was thinking why or what is it and whats is going wrong. So i was reading something more about GRUB Manual over the network and in a special chapter say if you need grub in your grub-mkimage use grub-mkrescue and chosse the grub-mkimage file when you are creating the output file and this gonna make a new iso with the mkimage with GRUB add for boot and the mkimage for load your system disk.

And was right!! i created the iso and all was right, GRUB LOADING with grub-mkrescue and the grub-mkimage loading in the ISO with the EFI property for boot. Try it if in other macines work and tell me news if something happend.

Added to this is add the files from your instructions to the ISO because only is boot rescue mode with bootloader for be more complex with the original and there it is.

Now, bad point by the way for new Ubuntu distribution, Secure Boot doesnt work because the signature is not valid that is imported by the system when is creating. i will see if i can do something but i think doesnt work in anyways.

So, reconstruyed ISO for no Secure Boot for CD-ROM and perhaps in other machines works with EFI comming soon.

Grettings to you guys and we will see you more.

Bye Bye.

And sorry for the time. JAJAJAJ.

**Comment by jhonnynemonic** [comment]
I wanna comment this new update my friend. In this case this the iso with uefi tools for regoster a source kernel compiled for use in pc adding the key .der in your machine and test how can run signed kernel with your tutorial for create boot cd.
This cd comtents two version but u need disable secureboot first for load the key. And rwboot for put again the secureboot and run the limix kernel with busybox like rootfs for boot minimal system.

I give you this treasure for the help and too you can see this.

Bye bye and happy cristmas!
https://drive.google.com/file/d/1T04gh58fKuA0gIRL06wUkjTdZAhvertJ/view?usp=drivesdk

**Comment by jhonnynemonic** [comment]
The real link.

https://drive.google.com/file/d/1mrvdO9KoZHnNrYHsnhQDHqorQH-T5U91/view?usp=drivesdk

**Comment by jhonnynemonic** [comment]
With the tool keytool you need execute binary and seaech mmx64.efi for register .der and restart.

**Comment by jhonnynemonic** [comment]
Hello again my friend.

I finish all the project working with UEFI and secureboot with a few things. Look and tell me what you think.

This version have certificates for work with secureboot and can be added to the system if you use key management in the bios for adds or if your pc run linux updating keys with a command that is on the web.

Just add all .der files and will work. The reason of this is the cause of the time get it doing it. And in this file if you take your time making a exam you will see all signed files for example using sbverify and sbsign commands

If anyone fails because the time of valid life end work with a few time pass only need sign again with a new certificate. Try openssl and this too can do with linux system.

All this was created following the ubuntu and wiki instructions on the internet. Nice by the way. And you portal for create the iso file.

Pherhaps isnt full but this version works and have a gew aspects of the news of grub2. Like VHD disk entrys for access to .iso files.

Take it and anyone can test and look or say something if wanna participate for example with how end the full distribution with desktop of linux can help and is wellcome.

Regards.

https://drive.google.com/file/d/1WPQH2AYAudiHb2cOkLLv7oJJ_YV-zk6M/view?usp=sharing

Bye and thank you

**Comment by jhonnynemonic** [comment]
Bye bye
